services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./api/.env