services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    container_name: api-kusodu
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - database
    networks:
      - kusodu

  postgres:
    image: postgres:17.1-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - kusodu

networks:
  kusodu:
    driver: bridge