services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./api/.env
    networks:
      - kusodu

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    networks:
      - kusodu


  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"

networks:
  kusodu:
    driver: bridge