services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./api/.env
    restart: always
    depends_on:
      - postgres
    networks:
      - kusodu

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./client/.env
    restart: always
    depends_on:
      - api
    networks:
      - kusodu

  postgres:
    image: postgres:17.1-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kusodu

networks:
  kusodu:
    driver: bridge

volumes:
  postgres_data:
