services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./api/.env
    restart: always
    networks:
      - kusodu

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./client/.env
    restart: always
    networks:
      - kusodu

networks:
  kusodu:
    driver: bridge