services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./api/.env
    restart: always