name: Lightsail Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Config SSH agent
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      # Add Lightsail SSH key to known_hosts
      - name: Add Lightsail SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts

      # Push code to the server
      - name: Push code to the server
        run: |
          rsync -avz --delete --exclude='.git*' --exclude='node_modules' ./ ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_IP }}:/home/${{ secrets.LIGHTSAIL_USERNAME }}/Kusodu

      # Create .env files
      - name: Déployer les variables d'environnement
        run: |
          ssh -T ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
            echo "${{ secrets.CLIENT_ENV }}" > /home/${{ secrets.LIGHTSAIL_USERNAME }}/Kusodu/client/.env
            echo "${{ secrets.API_ENV }}" > /home/${{ secrets.LIGHTSAIL_USERNAME }}/Kusodu/api/.env
            echo "${{ secrets.INFRA_ENV }}" > /home/${{ secrets.LIGHTSAIL_USERNAME }}/Kusodu/.env
          EOF

      # Start containers
      - name: Start containers
        run: |
          ssh -T ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
          cd /home/${{ secrets.LIGHTSAIL_USERNAME }}/Kusodu
          docker compose down
          docker compose -f docker-compose.prod.yml up -d --build
          docker ps
          EOF
